name: CI Build
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch on Push and any branches on PR
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'
env:
  CI: true

jobs:
  run:
    strategy:
      fail-fast: false
      matrix:
        node: [14, 16]
        platform: [ubuntu-latest]

    name: '${{matrix.platform}} / NodeJS ${{ matrix.node }}'
    runs-on: ${{matrix.platform}}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2 # codecov-bash seems to require this

      - name: Install pnpm itself
        uses: pnpm/action-setup@v2.2.2
        with:
          version: 7

      - name: Set NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'

      - name: Display Node & pnpm versions
        run: |
          node --version
          pnpm --version

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Run pnpm install dependencies
        run: pnpm install

      - name: Cache TypeScript and Jest
        uses: actions/cache@v3
        with:
          path: |
            packages/*/lib
            packages/*/tsconfig.tsbuildinfo
            test/.jest-cache
          key: ts-jest-${{ matrix.platform }}-${{ matrix.node }}-${{ github.run_id }}
          restore-keys: ts-jest-${{ matrix.platform }}-${{ matrix.node }}-

      - name: Run all workspace TSC builds
        run: pnpm build

      - name: Run Jest unit tests
        if: "!contains(github.event.head_commit.message, 'chore(release)')"
        run: pnpm jest:ci

      - name: Upload Jest coverage to Codecov
        if: "!contains(github.event.head_commit.message, 'chore(release)')"
        run: bash <(curl -s https://codecov.io/bash)